# Generated by Django 5.0.4 on 2024-05-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('category',), 'verbose_name_plural': ('categories',)},
        ),
    ]
