# Generated by Django 5.0.4 on 2024-05-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('category',), 'verbose_name_plural': 'categories'},
        ),
    ]
